### ISSUE TITLE
Global is not defined

### ISSUE THREAD

**Issue by PlaidTactician** [formio/angular-formio#165] opened 2018-04-10 16:23 UTC
I get this error when using angular-formio: 2.0.0-alpha.2 in angular 6.0.0-rc.4.

`Uncaught ReferenceError: global is not defined
    at Object../node_modules/formiojs/lib/formio.js (formio.js:1382)
    at __webpack_require__ (bootstrap:74)
    at Object../node_modules/formiojs/lib/formio.form.js (formio.form.js:23)
    at __webpack_require__ (bootstrap:74)
    at Object../node_modules/formiojs/lib/index.js (index.js:8)
    at __webpack_require__ (bootstrap:74)
    at Object../node_modules/angular-formio/formio.service.js (formio.service.js:1)
    at __webpack_require__ (bootstrap:74)
    at Object../node_modules/angular-formio/index.js (formio.service.js:112)
    at __webpack_require__ (bootstrap:74)
    at Object../src/app/app.module.ts (app.component.ts:8)
    at __webpack_require__ (bootstrap:74)
    at Object../src/main.ts (environment.ts:17)
    at __webpack_require__ (bootstrap:74)
    at Object.0 (main.ts:14)
    at __webpack_require__ (bootstrap:74)
    at checkDeferredModules (bootstrap:43)
    at Array.webpackJsonpCallback [as push] (bootstrap:30)
    at main.js:1
15:56:27.559 `

This is the line it points to:
`// Support ES5 require and globals.
module.exports = global.Formio = Formio;
exports.default = Formio;`

If you try to reproduce make sure to change  
`import { Observable} from 'rxjs/Observable'` 
to 
`import { Observable} from 'rxjs'`. 

Thanks

**Comment by SarathkumarMS** [comment] 2018-07-25 11:59
I get same error when using angular-formio: 2.0.0-rc.3 in angular 6.0.8.

Uncaught ReferenceError: global is not defined
    at Object../node_modules/crossvent/node_modules/custom-event/index.js (index.js:2)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/crossvent/src/crossvent.js (crossvent.js:3)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/dragula/dragula.js (dragula.js:4)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/formiojs/WebformBuilder.js (WebformBuilder.js:15)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/formiojs/FormBuilder.js (FormBuilder.js:13)
    at __webpack_require__ (bootstrap:81)

This error shown in index.js file and the line points to:
      var NativeCustomEvent = global.CustomEvent;

**Comment by SarathkumarMS** [comment] 2018-07-25 13:05
I found a solution for this issue, actually this error caused from another node_module package 'crossvent' 
So please add `(window as any).global = window;` to polyfills.ts (add at the top)

**Comment by noman115pk** [comment] 2018-09-05 10:54
@SarathkumarMS This solution works.

**Comment by vedbhawsar** [comment] 2018-10-18 08:47
I faced the same issue and solved with the polyfills.ts hack. The issue is occurring on angular 6, below are the details :

Angular CLI: 6.0.7
Node: 8.9.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.7
@angular-devkit/core         0.6.7
@angular-devkit/schematics   0.6.7
@schematics/angular          0.6.7
@schematics/update           0.6.7
rxjs                         6.2.0
typescript                   2.7.2

**Comment by desoga10** [comment] 2019-07-08 13:18
Add the code below in your index.html file. This is what worked for me.

<script> if (global === undefined) { var global = window; } </script>

**Comment by travist** [comment] 2019-08-29 02:16
This is now fixed in latest builds.

**Closed by travist** 2019-08-29 02:16 UTC
